# Generated by Django 5.2 on 2025-04-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to='event_flyers/'),
        ),
    ]
