# Generated by Django 5.2 on 2025-04-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('organizer', 'Event Organizer'), ('vendor', 'Vendor'), ('admin', 'Admin'), ('guest', 'Guest')], default='guest', max_length=10),
        ),
    ]
